server:
  port: 3355
spring:
  application:
    name: cloud-config-client-3355
  consul:
    host: localhost
    port: 8500
    discovery:
      service-name: cloud-config-client
      instance-id: ${spring.application.name}
config:
  info: infoVersion5
  msg: msgVersion5

